### PR TITLE
fix: outputPath as subfolder 

### LINKED ISSUE #606: outputPath as subfolder
Thanks for great toolkit!
If I use subfolder as an output path `outputPath: 'assets/built'` it breaks the dynamic import functionality because of the wrong variable name.
```js
/* wpack.io publicPath */
window.__wpackIotestassets/built='https://www.wp.local/wp-content/themes/test/assets/built/';
```
```js
window["__wpackIo".concat("test").concat("assets/built")]
```
I think appname and outputPath should be escaped/sanitized.
For example, WP has `sanitize_key()` function for this.

### PR DESCRIPTION
**Pull request by TrilipuT**
fix #606 
should be merged after https://github.com/swashata/wpackio-enqueue/pull/6

### CODE REVIEW

File: packages/entrypoint/src/index.ts [hunk 1]
```diff
@@ -15,8 +15,9 @@ declare const window: { [x: string]: any };
 
 // We would override __webpack_public_path__ only if __WPACKIO__ webpack plugin is set
 if (__WPACKIO__) {
+	const path = (__WPACKIO__.appName + __WPACKIO__.outputPath)
+		.toLowerCase()
```
Comment (swashata) [inline packages/entrypoint/src/index.ts]: Any particular reason why you've opted for `.toLowerCase`? Is it because of `sanitize_key` from WordPress API?

**Comment by swashata** [comment]
Thank you @TrilipuT 	for your contribution. I will also take a look at the PHP library one.

File: packages/entrypoint/src/index.ts [hunk 2]
```diff
@@ -15,8 +15,9 @@ declare const window: { [x: string]: any };
...
+		.replace(/[^a-z0-9_-]/, '');
```
Comment (swashata) [inline packages/entrypoint/src/index.ts]: This should be

```suggestion
		.replace(/[^a-z0-9_\-]/g, '');
```

Without this (`/g`), only the first instance of not accepted characters would be replaced. :)

File: packages/entrypoint/src/index.ts (hunk 1 above)
Comment (TrilipuT) [reply packages/entrypoint/src/index.ts]: Yes, just because of it. But I assume that it can break backward compatibility for those who generating this variable manually. What do you think?

Comment (TrilipuT) [reply packages/entrypoint/src/index.ts]: Removed this. I think better not to break backward compatibility

**Comment by swashata** [comment]
Hey a quick update that I see some failed things on CI

1. Due to prettier error.
2. Something going on with HMR.

I will take a look next week when I have some time :) Thank you for your contribution and patience with this 😄

File: packages/entrypoint/src/index.ts (hunk 1 above)
Comment (swashata) [reply packages/entrypoint/src/index.ts]: I think I will merge this and do some testing...
